apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sofia-kalinina/real-gitops.git
    targetRevision: main
    path: charts/app2
    helm:
      valueFiles:
        - ../../argocd/prod/real-gitops/global-values.yaml
        - ../../argocd/prod/real-gitops/app2/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: real-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
