apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
    {{ include "common.ingress.tls" . }}
    rules:
        - host: app2.{{ include "common.ingress.domain" . }}
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: app2
                  port:
                    number: 80


Ingress.networking.k8s.io "app1" is invalid: spec.rules[0].http.paths[0].backend: Required value: port name or number is required