apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
data:
  url: <base64-encoded-repository-url>
  username: <base64-encoded-github-username>
  password: <base64-encoded-personal-access-token>
